# Generated by Django 5.1.5 on 2025-01-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(unique=True)),
                ("alt", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("stored_name", models.CharField(max_length=255)),
                ("relative_path", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("is_public", models.BooleanField(default=False)),
                ("checksum", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stored_files",
            },
        ),
    ]
