# Generated by Django 5.1.5 on 2025-03-06 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stored_file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
