# Generated by Django 5.1.5 on 2025-01-31 19:58

import django.db.models.deletion
import src.modules.user.domain.enums.user_gender_enum
import src.shared.domain.enums.status_enum
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("organization", "0001_initial"),
        ("role", "0001_initial"),
        ("stored_file", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=src.modules.user.domain.enums.user_gender_enum.UserGender.choices,
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=src.shared.domain.enums.status_enum.Status.choices,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stored_file.storedfile",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="role.role"
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
