# Generated by Django 5.1.5 on 2025-02-05 14:44

import src.shared.domain.enums.status_enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    (src.shared.domain.enums.status_enum.Status["ACTIVE"], "ACTIVE"),
                    (
                        src.shared.domain.enums.status_enum.Status["DISABLED"],
                        "DISABLED",
                    ),
                    (src.shared.domain.enums.status_enum.Status["BLOCKED"], "BLOCKED"),
                    (src.shared.domain.enums.status_enum.Status["WAITING"], "WAITING"),
                ],
                max_length=10,
            ),
        ),
    ]
