# Generated by Django 5.1.5 on 2025-02-14 17:03

import src.shared.domain.enums.status_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_is_active_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=src.shared.domain.enums.status_enum.Status.choices,
                max_length=10,
            ),
        ),
    ]
