services:
  app:
    user: root
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "${PORT}:8080"
    volumes:
      - ~/.m2:/root/.m2
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    driver: local
