services:
  app:
    user: root
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '${PORT}:5173'
    command: sh -c "npm install && npm run dev -- --host"
