services:
  app:
    user: root
    build: .
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - '${PORT}:8000'
    depends_on:
      - db

  cli:
    user: root
    build: .
    volumes:
      - .:/app
    command: 'tail -f /dev/null'
  db:
    image: postgres:14
    restart: always
    tty: true
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    driver: local
