# Generated by Django 5.1.5 on 2025-01-31 19:58

import django.db.models.deletion
import src.modules.role.domain.enums.ability_actions_enum
import src.modules.role.domain.enums.ability_codes_enum
import src.modules.role.domain.enums.role_references_enum
import src.shared.domain.enums.status_enum
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        choices=src.modules.role.domain.enums.ability_codes_enum.AbilityCodes.choices,
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=src.modules.role.domain.enums.ability_actions_enum.AbilityActions.choices,
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "abilities",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=src.shared.domain.enums.status_enum.Status.choices,
                        max_length=50,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        choices=src.modules.role.domain.enums.role_references_enum.RoleReferences.choices,
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="company.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="RoleAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="role.ability"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="role.role"
                    ),
                ),
            ],
            options={
                "db_table": "role_abilities",
                "unique_together": {("role", "ability")},
            },
        ),
    ]
