# Generated by Django 5.1.5 on 2025-01-31 19:58

import django.db.models.deletion
import src.shared.domain.enums.status_enum
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0001_initial"),
        ("stored_file", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                src.shared.domain.enums.status_enum.Status["ACTIVE"],
                                "ACTIVE",
                            ),
                            (
                                src.shared.domain.enums.status_enum.Status["DISABLED"],
                                "DISABLED",
                            ),
                            (
                                src.shared.domain.enums.status_enum.Status["BLOCKED"],
                                "BLOCKED",
                            ),
                            (
                                src.shared.domain.enums.status_enum.Status["WAITING"],
                                "WAITING",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="address.address",
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="stored_file.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
            },
        ),
    ]
